### ISSUE TITLE
Deauther 2.1.0 on WeMos D1 Mini(ESP8266) - Battery Level

### ISSUE THREAD

**Issue by Ch4ist0** [SpacehuhnTech/esp8266_deauther#1112]
Hello, I am using the WeMos D1 mini system (ESP8266) is it possible to change the battery level options in the menu Deauther 2.1.0 instead of "clock"?

**Comment by TheMiguelBi** [comment]
How did you manage to run version 2.1 on wemos d1 mini ?? O.O

**Comment by spacehuhn** [comment]
>  change the battery level options

Not sure I fully understand your question, but you need extra hardware to read the battery voltage. Such a feature is not implemented so you'd have to code it yourself.

**Comment by LmfaoHax** [comment]
> 
> 
> > change the battery level options
> 
> Not sure I fully understand your question, but you need extra hardware to read the battery voltage. Such a feature is not implemented so you'd have to code it yourself.

hello there
how can we define if there is more menu nodes so it goes to next page?
for example if i add a new option on the menu so they become 6 options but only 5 can be displayed (while my oled is big enough and configured if there would be more content ) ?

i can see there are somethings about this in void DisplayUI::drawMenu()
but cant figure which part is designed for this ( going to next page if there are more options than 5 )


`    int    row = (currentMenu->selected / 4) * 5; // /5`

i edited the above value to 4 to check if the clock would go to next page and it kinda works but the problem is that when it goes to next page its blank and i cant see "CLOCK" option

**Comment by Bommlon** [comment]
@GrandJohnny I'm not sure how this is connected to this issue. Please open a new one if you don't mind. It would make it easier for other people with the same question to find it.

**Comment by LmfaoHax** [comment]
> 
> 
> @GrandJohnny I'm not sure how this is connected to this issue. Please open a new one if you don't mind. It would make it easier for other people with the same question to find it.

#1314
